### DISCUSSION TITLE
When deploying from GitLab pipeline the branch inside Vercel is HEAD not the current merge request branch

### DISCUSSION THREAD

**Discussion by Totara-thib** [vercel/vercel#10199] [Help] [answered]
## Context

When i try to deploy into a preview environment from a merge_request branch pipeline with the https://vercel.com/guides/how-can-i-use-gitlab-pipelines-with-vercel job template, the branch inside Vercel become `HEAD`, that's not the case if i let the webhook deploy the app after a commit.

That's an issue because when i'm triggering a pipeline from a merge_request branch i'm assigning the branch to a custom domain, that doesn't work if the branch is `HEAD`
![image](https://github.com/vercel/vercel/assets/78480448/47340e23-40d9-4cef-9167-5aed867ea326)

## Expected behavior

Add in the CLI the possibility to add the current branch at the `pull` or `deploy` command:

```
    - vercel pull --yes --environment=preview --git-branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME --token=$VERCEL_TOKEN
```
or
```
    - vercel deploy --prebuilt --git-branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME --token=$VERCEL_TOKEN
```
or Vercel automatically grab the current branch from the job

**Comment by Totara-thib** [comment, marked as answer]
I've found a way to resolve my issue for my use case:

Using the CLI keyword `alias` I was able to manually set my custom domain for the preview job and the production job, `$VERCEL_AUTOMATIC_PROD_URL` is the static url set by vercel

here's my GitLab configuration:

```yml
deploy_preview:
  image: node:16
  before_script:
    - mv .gitlab/environments/config.preview.json environments/config.json
  stage: deploy
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_SLUG
    - vercel build --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_SLUG
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_SLUG
    - vercel alias set $VERCEL_AUTOMATIC_PREVIEW_URL $VERCEL_PREVIEW_CUSTOM_DOMAIN --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_SLUG
  rules:
    - when: manual

deploy_production:
  image: node:16
  stage: deploy_prod
  before_script:
    - mv .gitlab/environments/config.prod.json environments/config.json
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_SLUG
    - vercel build --prod --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_SLUG
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_SLUG
    - vercel alias set $VERCEL_AUTOMATIC_PROD_URL $VERCEL_PROD_CUSTOM_DOMAIN --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_SLUG
```
If i don't specify the scope of my team it always try to use the domain and project under my user namespace.
