### DISCUSSION TITLE
Deploying Hexo project reported an error

### DISCUSSION THREAD

**Discussion by imjiaoyuan** [vercel/vercel#10421] [Help]
### Question

I used a self hosted Gitlab to store the code for the Hexo project and deployed the project to Vercel through the CI/CD function. Previously, it was correct, but today I reported an error after pushing the update. The error content is as follows

```yml
$ vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
Vercel CLI 32.1.0
Retrieving project…
Deploying hieroglyphs/kettle
Uploading [--------------------] (0.0B/126.8KB)
Uploading [=======-------------] (45.2KB/126.8KB)
Uploading [===========---------] (76.0KB/126.8KB)
Uploading [================----] (106.7KB/126.8KB)
Uploading [====================] (126.8KB/126.8KB)
https://kettle-2020oy0xb-hieroglyphs.vercel.appinspect/: https://vercel.com/hieroglyphs/kettle/5b75rH9szcCJ4bREufBqrEDg9ESa [4s]
Queued
Building
Error: Command failed with exit code 1: du -ms /vercel/path0/node_modules
du: cannot access ‘/vercel/path0/node_modules’: No such file or directory
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

The content of my CI/CD configuration file is as follows

```yml

default:
  image: node:16.16.0

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
```
