### DISCUSSION TITLE
How can I specify which project vercel deploy should execute the deploy?

### DISCUSSION THREAD

**Discussion by lucashfreitas** [vercel/vercel#10775] [Help]
### Question

The CLI doesn't have an option to specific a `--project` flag and the `--scope` just specify the org.

I am running the deploy in a CI/CD and vercel created a new project, but I am curious to know how does vercel cli `guesses` which project we want to work on.

**Comment by gersanco** [comment]
Hi @lucashfreitas 

This works for me on github actions. Set the VERCEL_PROJECT_ID before deployment. I mean, what I discovered was that VercelCLI is uploading the VERCEL_PROJECT_ID so, what I did was see the correct one that I wanted to upload.

```
- name: Deploy to Vercel ${{env.APP_NAME}} - ${{env.ENVIRONMENT}}
        env:
          VERCEL_PROJECT_ID: ${{ steps.get_project_id.outputs.project_id }}
        run: vercel --token=${{secrets.VERCEL_TOKEN}} --scope=${{secrets.VERCEL_ORG_ID}} --no-wait ${{env.PRODUCTION_FLAG}}
        shell: bash
```
