### DISCUSSION TITLE
How to prevent preview deployments from being overwritten ? CI/CD

### DISCUSSION THREAD

**Discussion by johnymanuelli** [vercel/vercel#10901] [Help]
### Question

Hello,
how to prevent preview deployments from being overwritten every time I deploy the main branch ? 

This is my .gitlab-ci.yml
````yaml
image: node:18.14

stages:
  - deploy

deploy to dev:
  stage: deploy
  except:
    - main
  when: manual
  script:
    - npm install --location=global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN --force
    - vercel build --token=$VERCEL_TOKEN --force
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN --force

deploy to production:
  stage: deploy
  only:
    - main
  when: manual
  script:
    - npm install --location=global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN


````

Thanks.
