### DISCUSSION TITLE
github action now deployment with `--scope` still asks for scope

### DISCUSSION THREAD

**Discussion by iamdevlinph** [vercel/vercel#4015] [General] [answered]
I encountered this locally and was easily remedied since I can interact with it

![image](https://user-images.githubusercontent.com/19337229/78504890-6fa96080-77a2-11ea-8714-d1f9054cc5c8.png)

But how can I avoid this when using with Github actions when there is no interaction? I've already provided the scope and the scope is the one listed in `now switch`

![image](https://user-images.githubusercontent.com/19337229/78504912-818b0380-77a2-11ea-9b4e-9d389e46b093.png)

![image](https://user-images.githubusercontent.com/19337229/78504913-8354c700-77a2-11ea-918e-ea376c3d1e55.png)

[Link to the github action if anyone's interested](https://github.com/iamdevlinph/next-ts-firebase-pwa/pull/36/checks?check_run_id=562321799)

**Comment by paulogdm** [comment]
Hello,

It is not asking for the scope, but that you do the project linking. If you need a CI/CD environment-like behavior, you can do:
```
NOW_ORG_ID=$ORG NOW_PROJECT_ID=$PROJET now -t $TOKEN --prod
```

**Reply by iamdevlinph** [reply]
What if I want to deploy it on my personal account?

I tried my username and email but no luck.

**Reply by iamdevlinph** [reply]
Is team different from organization? I created a team called `iamdevlinph-deploys` in zeit but i got this error from `now`

```
Error! Organization not found ({"NOW_ORG_ID":"iamdevlinph-deploys"}
```

**Reply by iamdevlinph** [reply]
I think I misunderstood the ORG_ID and PROJECT_ID lol. I just read to check on the `.now` folder for these stuff

**Reply by paulogdm** [reply]
Gald you sorted this :smile:

**Reply by chabou** [reply]
It could be useful to add these env var in [Project Linking documentation page](https://zeit.co/docs/now-cli#commands/Now/project-linking). I took some times to figure out how to do this.

**Comment by iamdevlinph** [comment, marked as answer]
Got it by following what's shown on this [article](https://sergeyfilimonov.com/blog/deploy-team-zeit-now/)

I previously had it like so
```
    steps:
      - uses: actions/checkout@v1 # Get last commit pushed
      - name: Deploying on Zeit
        run: NOW_ORG_ID=$ORG NOW_PROJECT_ID=$PROJET yarn client:deploy:dev --scope iamdevlinph --token $ZEIT_TOKEN
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }} # Passing github's secret to the worker
          ORG: ${{ secrets.ORG_ID }}
          PROJECT: ${{ secrets.PROJECT_ID }}
```
But it's complaining that the projectId is not found or something. So I just copied the one from the article.

```
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
          now-org-id: ${{ secrets.ORG_ID }}
          now-project-id: ${{ secrets.PROJECT_ID }}
```
