### DISCUSSION TITLE
how to enable cache with bitbucket pipeline

### DISCUSSION THREAD

**Discussion by dohomi** [vercel/vercel#4151] [General] [answered]
Hi Guys,

I'd like to know how a recommended bitbucket pipeline config would look like. I receive following warning:
```
Warning: No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache
```

I added now following yml
```
image: node:10.15.3

definitions:
  caches:
    nextcache: .next/cache

pipelines:
  default:
    - step:
        caches:
          - node
          - nextcache

        script: # Modify the commands below to build your repository.
          - npm install
```
What else need to be included in the pipeline if I have a NextJS SSG project? Thanks!
