### DISCUSSION TITLE
Using the preview URL from Vercel for Github app in a Github Action

### DISCUSSION THREAD

**Discussion by patrickedqvist** [vercel/vercel#4501] [Help] [answered]
Hello Community,

Is it possible to use a preview URL generated by the Vercel for Github app in a Github Action? So far I've only seen it possible by using the [Vercel Action](https://github.com/marketplace/actions/vercel-action)

My goal is to run automated lighthouse tests and since we are using the Github App for preview deployments it would be neat to utilize that instead of running the Vercel Action.

So for this is what my action looks like

```.yml
name: Lighthouse

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        id: vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_TEAM_ID }}
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          prCommentEnabled: true
          urls: ${{ steps.vercel.outputs.preview-url }} 
```

**Comment by styfle** [comment, marked as answer]
The Vercel GitHub integration creates deployments and notifies GitHub's API of the deployment URL.
So you can use the GitHub API to read the deployment URL.

![image](https://user-images.githubusercontent.com/229881/83079962-f6fcad00-a04a-11ea-890c-486bf70e3e55.png)

For example, fetch `https://api.github.com/repos/:user/:repo/deployments` and find the `statuses_url`.
Fetch that `https://api.github.com/repos/:user/:repo/deployments/:status/statuses` and this will have a `target_url`.

Alternatively, you can use a service like Checkly which integrates very easily https://blog.checklyhq.com/easy-automated-e2e-testing-monitoring-for-your-frontend-with-vercel-and-checkly-3/

**Comment by patrickedqvist** [comment]
Thanks for the answer. I wrote a little Github action (atm not available on the marketplace) based on this approach https://github.com/patrickedqvist/wait-for-vercel-preview

**Comment by yn5** [comment]
[This article](https://webcloud.se/blog/2020-02-16-github-actions-preview-deploys/) shows how to use the `deployment_status` event and get the preview URL from the event’s payload.

```
name: Successful Deploy Action Example
on: deployment_status
jobs:
  build:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: XYZ
        run: npm run xyz
        env:
          DEPLOY_URL: ${{ github.event.deployment_status.target_url }}
```
