### DISCUSSION TITLE
Vercel Github integration... running tests?

### DISCUSSION THREAD

**Discussion by fishactual** [vercel/vercel#4589] [Help] [answered]
How are people that are using the Vercel Github integration running their tests? I don't want a preview deployment (or any deployment really) until all of my tests have passed. Is there a recommended way of doing this?

**Comment by markozxuu** [comment, marked as answer]
Good question ! I had the same doubt as you some months ago. I fixed the problem using **GitHub Actions** and a Vercel [plugin](https://github.com/marketplace/actions/vercel-action) (formerly ZEIT)

Your file should look like this:

```
name: Main workflow

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
  deploy_now:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - name: deploy
          uses: actions/zeit-now@master
          env:
            ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
```

I could see in detail my configuration repository [here](https://github.com/markozxuu/github-action) : )

**Reply by fishactual** [reply]
Awesome, thank you for sharing that!

**Reply by nikitalpopov** [reply]
@markozxuu where should I set `secrets.ZEIT_TOKEN`?

**UPD:** [there](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository)

**Reply by thesobercoder** [reply]
@markozxuu Do you need to uninstall the Vercel Github plugin in that case so that auto-deployment doesn't trigger on push?

**Reply by tomascarignano98** [reply]
This is what I did, and it worked perfectly for me, only that today the implementation looks a bit different.

The steps I followed were:
1. Disconnect your vercel project from the github repository. This way we prevent any deployments whenever a github workflow fails.
![Screenshot from 2023-02-02 18-33-06](https://user-images.githubusercontent.com/75227199/216454653-120cbcf6-6d7c-449f-b196-963de1baabdc.png)
2. Create a github workflow where you essentially test and deploy your application. We can achieve that with the use of the [Vercel Action plugin](https://github.com/marketplace/actions/vercel-action). Take a look at this example of mine.
```
name: Test & Deploy Website

on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test_deploy"
  test_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn install
      - name: Install Firebase CLI
        run: npm i firebase-tools -g
      - name: Cache Firebase Emulators
        uses: actions/cache@v3
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
      - name: Test
        run: firebase emulators:exec "yarn test"
      - name: Deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          vercel-version: 28.15.0

```

### Additional Info.

You'll need to [set repository secrets in GitHub Action Secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository).
![Screenshot from 2023-02-02 19-08-41](https://user-images.githubusercontent.com/75227199/216460506-34e9a978-ab00-4e17-aa60-1e70fd2ad644.png)

Okay, how do you get these Vercel tokens? 
- VERCEL_TOKEN: you'll need to [create a token named VERCEL_TOKEN](https://vercel.com/account/tokens).
- ORG_ID and PROJECT_ID: you can easily get these following [these steps](https://github.com/marketplace/actions/vercel-action#project-linking).
