### DISCUSSION TITLE
CLI Deploy to different domains

### DISCUSSION THREAD

**Discussion by reed-jones** [vercel/vercel#4622] [Help]
Currently I have git integration, so the main 'live' site is automatically deployed from my `master` branch, and a separate test site is deployed to a different domain from my `dev` branch. 

I have a bit of a difficult build step which I can't seem to get it to work on vercel, so I have been compiling everything using github actions & commiting the dist right to the branches for vercel to pick up. This works fine, except now I need to commit the production bundles to the repo.

Is there a way to deploy to different domains/branches using the CLI? This would make it really easy to deploy from the CI

```
npm install
npm run prod
vercel --prod --domain dev.example.com
```

```
npm install
npm run prod
vercel --prod
```

I tried just `vercel` to get a deployment preview, however it seemed to go to the default vercel domain, not my custom configured 'dev' one.

**Comment by davidbalivo** [comment]
I'm running into a similar issue. Like many teams, we have `dev`, `staging` and `master` branches and we use **CircleCI** for CI/CD. 

I configured 3 different domains, (mydomain.com, dev.mydomain.com, staging.mydomain.com) and I linked each of them to the specific branch.

So far, I was using hooks to deploy from CircleCI. It was not ideal, as the code deployed was the one from  Bitbucket and not the "local one" from CircleCI, but based on my needs it would work.

Now things have changed as I need to add environment variables. Based on the docs and tests I've done already, I can have a `.env` file and the variables will be exported, but for security reasons, I can not add the `.env` file to my Bitbucket repository. The common solution here would be to create this file during the building process on CircleCI, but, as I'm using hooks, the code deployed is the one from Bitbucket.

The proper approach to me would be, instead of using hooks, execute the vercel `command` in a similar way @reed-jones suggested above:

```vercel --prod --domain myDomainBasedOnBranch.com```

Is there any way to achieve it? or is there perhaps a different path to achieve what I what to do?

**Comment by jonyw4** [comment]
I need a solution to this too! 😁

**Comment by devoncmather** [comment]
Agreed, also looking for a solution to this. Funny.. you can buy a domain through the CLI but not deploy to it 🙁

**Comment by mehmet-tansu-isikli** [comment]
+1 I need this too 😕

**Comment by nickdandakis** [comment]
Running into the same issue.

I have a staging-specific environment variables set in Preview, and only want those applied to a specific custom domain.
Running `vercel --prod` to deploy production-specific environment variables in Production also deploys to all custom domains for the project, which essentially turns my staging into production..

**Reply by DeBraid** [reply]
Same Issue I am facing while setting ENV variables via web GUI https://vercel.com/{__USERNAME__}/{__PROJECT__}/settings/environment-variables

**Expected:** I should be able to set an env variable, `API_URL`,  to distinct value for a specific deployment environment. 
**Actual:** All values are the same following a deploy.  Deploying to production will alter the value of `API_URL` in the preview environment.

**To reproduce:** 

Hit the `Preview` tab and set ENV variable `API_URL` to `staging.url.com/api`,  and then run `vercel`, everything works fine on Preview mode (my staging env).
 
Then move over to the Production tab on Vercel web GUI and set same ENV variable `API_URL` to `url.com/api` then run `vercel --prod`.  Production env works fine, but the Preview environment buggy as it now points to the wrong URL: `url.com/api` instead of `staging.url.com/api`?

Love to know what I am doing wrong here.  Should I avoid the Vercel Env Variable web GUI and use `.env` files?

**Comment by Minasokoni** [comment]
For all you guys who still have this issue. I got around it by having an environment variable for each site (e.g: ENV=dev,qa,prod). When I want to deploy to a specific env i use:
1. `vercel --build-env ENV=<env>`. I get a specific preview url for the env. I then use the alias command: 
2. `vercel alias <preview url I got from the first command> <domain of the site I want to use>`

I know its not a great idea if you have multiple env variables you need to set, but you can just put everything into a  script or use the vercel api

edit: so many typos wow. :D

**Reply by reed-jones** [reply]
Oh thanks! That's a good idea, I'll have to give that a shot

**Reply by paulogdm** [reply]
Using `vercel alias` is not recommended. Please refer to https://vercel.com/knowledge/using-vercel-cli-for-custom-workflows

**Reply by nickdandakis** [reply]
So @paulogdm, is the recommendation here to create a separate project per environment and point to a custom `vercel.json`?

(I didn't know `vercel alias` is not recommended)

**Reply by devoncmather** [reply]
@paulogdm I get the following error after following that article, I've created the custom project config at `.vercel/production.vercel.json`

```
Error! Couldn't find a project configuration file at
    ~/Projects/test-react-app/vercel.json or
    ~/Projects/test-react-app/now.json or
    ~/Projects/test-react-app/package.json
```

**Reply by devoncmather** [reply]
OK turns out i just needed an empty JSON file in the root directory and it worked 👍

**Reply by barraponto** [reply]
@paulogdm i wish that link was easier to find. there's no mention to those environment variables in the [vercel cli reference](https://vercel.com/docs/cli)

**Reply by DeBraid** [reply]
@devoncmather 

Could you elaborate more on the solution you settled on?

Are you creating many files like `*.vercel.json`?  How does this differ from using `.env.*`?  Thanks

**Reply by devoncmather** [reply]
I created two projects in Vercel, and then created two vercel jsons configs and then run them like so;

`VERCEL_ORG_ID=TEAM_ID_HERE VERCEL_PROJECT_ID=PROJECT_ID_HERE vercel --prod --scope betafashion -A vercel.production.json`

**Reply by hip1310** [reply]
@devoncmather I liked the way you deployed. Only problem I face with this, when multiple people are deploying using same, it's so hard to find particular deployment because no branch name is published for these deployments. Any solution you figured out for that?

**Reply by hip1310** [reply]
@devoncmather @paulogdm  Can you please suggest any solutions you guys found for my above question?

Also, if you are using vercel cli to deploy from some CI/CD tool like travis or circleci, you have to specify vercel token. I used token under my account and that worked. But when multiple people will be pushing I want to use token for those dynamically, for which I really don't have any idea. If you guys can help me with that.

**Reply by paulogdm** [reply]
The CLI can only be used with a personal token. We are not offering teams account nor we intend to.

We have a few features in our pipeline that will allow you to avoid the CLI + CI/CD:

- Support for GitHub Enterprise/GitLab self-hosted.
- Only deploy if checks were accepted. So you can run lints and other tests before Vercel attempts a deployment.

**Reply by khanakia** [reply]
`vercel --build-env ENV=development` not taking the `env.development` it still picking the `.env.production` file

**Reply by bunasQ** [reply]
@Minasokoni you saved me! thanks bro

**Comment by danaugrs** [comment]
Are there any better ways to do this now?

**Comment by mununki** [comment]
As per the previous discussion here, making another branch is the only solution to deploy the multiple environments?

**Reply by leerob** [reply]
Environments are branched based currently, correct: https://vercel.com/changelog/environments-variables-per-git-branch

Alternatively, you can dynamically load different values at runtime at the application level.

**Reply by kasvith** [reply]
hi @leerob 

most projects need to be deployed to different environments, like qa, uat, staging, prod
doing this with Vercel seems really counter-intuitive.

Vercel only provides 3 default envs and for most projects they doesn't make any sense.
Can you please improve this exp?

Since we also uses gh-actions, branch based git deployments are not really useful for us as well

**Comment by easyrun32** [comment]
I did this with github actions...
Here's what i did 

```
name: CI
on: [push]

jobs:
  # testing, building, linting for all branches
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Begin linting
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nodeModules-
      
      - name: Install dependencies
        run: npm install
      # - name: Run ESLint
      #   run: yarn lint


  deploy:
    runs-on: ubuntu-latest
    needs: lint

    # if main or dev branch go to steps
    if: github.ref == 'refs/heads/main' ||  github.ref == 'refs/heads/dev' 

  
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20 # some library for a cool guy
        id: vercel-deployment
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          # repo name
          vercel-project-name: 'website'
          # if main branch go to --prod environment otherwise nothing for preview environment
          vercel-args: "${{ github.ref == 'refs/heads/main' && '--prod' || '' }}"
          # if main branch deploy to production.domain.com otherwise go to dev.domain.com
          alias-domains: "${{ github.ref == 'refs/heads/main' && 'websitei.vercel.app' || 'devwebsitei.vercel.app' }}"



    # will show a pretty commit message after push 
    outputs:
      preview-url: ${{ steps.vercel-deployment.outputs.preview-url }}
```

**Comment by khanakia** [comment]
`vercel --build-env ENV=development` not taking the `env.development` it still picking the `.env.production` file

**Comment by danarchos** [comment]
After hours of trying to make this work on Vercel - I am now using Heroku where you can set all this up trivially before you even have your morning coffee.

**Reply by khanakia** [reply]
Their platform is great however they have poor support I faced many issues but I did not get a resolution to any of the issues. I had to solve all the issues myself. It seems like they do not care about customers anymore as they become so big.

**Comment by kasvith** [comment]
I hit the same wall :/

**Comment by temuujinya** [comment]
My simple solution was calling vercel alias after deploy. This is my gitlab-ci configuration.
```
default:
  image: node:16.16.0

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN --scope $TEAM_SLUG_SCOPE
    - vercel build --token=$VERCEL_TOKEN  --scope $TEAM_SLUG_SCOPE
    - PREVIEW_URL=$(vercel deploy --prebuilt --token=$VERCEL_TOKEN --scope $TEAM_SLUG_SCOPE)
    - vercel alias set $PREVIEW_URL <your_custom_domain> --token=$VERCEL_TOKEN  --scope $TEAM_SLUG_SCOPE
```

**Comment by gabrielfernandes-codes** [comment]
Similar to how @temuujinya posted, Vercel has an example of how you can achieve that on GitHub Actions: https://vercel.com/guides/how-to-alias-a-preview-deployment-using-the-cli

```
name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" your-alias.app
```
I agree that it could just be an option of the deployment itself, but the alias also works just fine. I currently have an implementation where I can build and deploy my branches for preview from GitHub with a custom CI/CD (without the Vercel app integration).

**Comment by tobiastornros** [comment]
Example if you have environment variables connected to a specific branch in Vercel. For example if you use `main` or `staging` branches as last step before production deploy. Add the **--git-branch** options to `vercel pull`

```
name: Vercel Staging Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    - your_branch
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --git-branch=your_branch --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" your-alias.app

```
