### DISCUSSION TITLE
How do deploy to Vercel with GitLab CI?

### DISCUSSION THREAD

**Discussion by errnesto** [vercel/vercel#4853] [Show and tell] [answered]
In my view the follwing setup leads to a deeper integration with gitlab than using the gitlab plugin. 
Beacuse it integrates with gitlab environments and review apps.
Also I don't have to set anything up at vercel (except creating a token)

I set the two env variables `VERCEL_TOKEN` and `VERCEL_SCOPE` all the others come from gitlab.

```yaml
deploy-to-vercel:
  stage: deploy
  image: node:13.10.1-alpine3.10

  variables:
    PREVIEW_URL=https://$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.$VERCEL_SCOPE.vercel.app

  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'master'

  environment:
    name: vercel/$CI_COMMIT_REF_NAME
    url: $PREVIEW_URL

  script:
    - npm i -g vercel
    - DEPLOYMENT_URL=$(vercel --name $CI_PROJECT_NAME --confirm -t $VERCEL_TOKEN)
    - vercel alias set $DEPLOYMENT_URL $PREVIEW_URL -t $VERCEL_TOKEN

```

Since I use `--name` a new project is created if none exists (so if I copy the repo - and add vercel token - I can deploy without setting up anything manually in the web ui).
And with `vercel alias` I can get the same behavior as with the plugin to get a url that will reflect the state of my merge request.
I could also have [set dynamic environment urls](https://docs.gitlab.com/ee/ci/environments/#set-dynamic-environment-urls-after-a-job-finishes) but I like the cleaner URLs

The sad thing is it took me really long to figure this out 

- `--name` is depricated (even though an alternative is promised: see #4021) Maybe this already works with linking when using `vercel --confirm`? I did not try it out…
- The `vercel alias` cli command is not documented (you can run `vercel alias -h` but you have to know the command exists) 
- Also the trick with getting the deployment url like this: `$(vercel)` Is something I picked up in a discussion somewhere.

I really like the super simple setup with the git integration, but to integrate in ci I think there is no way around the cli.

**Comment by patoncrispy** [comment]
This is really nice. Thanks for sharing! Really not enough documentation on this. My problem was I still wanted to run tests, etc. before deploying and there doesn't seem to be any flexibility here. Appreciate this solution.

**Comment by abdu355** [comment]
Yep, been running all over the internet looking for something like this. Never knew I could stumble upon amazing solutions ( to actual issues) in the discussion threads.
Thanks really.

**Comment by collie-moore** [comment]
Thank you for this. 
So if I have testing scripts in my gitlab-ci.yml I can add this below that right?

**Reply by ghost** [reply]
for me, it worked like this. I only needed to change the line `- vercel alias set ...`. This line caused some problems. Also I added `tags: `, but I don't know If this is necessary.

**Reply by ricky-sb** [reply]
I fixed the alias by removing `https://` from the `PREVIEW_URL` variable.

**Comment by ghost** [comment]
Thats really cool. I tried it and it worked nearly without any changes, thank you! The only thing, I´m not figuring out is: 
How can I use this when I have a Team in Vercel? It works perfectly fine in my private Vercel account, but I can't figure out how I can run the deployment in a team project in Vercel :/

**Reply by ricky-sb** [reply]
You have to add `--scope $VERCEL_SCOPE` to the last two commands.  Here's my full script:

```yaml
deploy-to-vercel:
  stage: deploy
  image: node:14

  variables:
    PREVIEW_URL: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.$VERCEL_SCOPE.vercel.app

  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'

  environment:
    name: vercel/$CI_COMMIT_REF_NAME
    url: https://$PREVIEW_URL

  script:
    - npm i -g vercel
    - DEPLOYMENT_URL=$(vercel --name $CI_PROJECT_NAME --confirm -t $VERCEL_TOKEN --scope $VERCEL_SCOPE)
    - vercel alias set $DEPLOYMENT_URL $PREVIEW_URL -t $VERCEL_TOKEN --scope $VERCEL_SCOPE
```

**Comment by oxfist** [comment]
Thanks for this great contribution! It’s kinda hard to get clear information on how to handle this and this helped me a lot!

Looking into the Vercel docs I ran into this: [Using Vercel CLI for Custom Workflows - Using the CLI Without Project Linking](https://vercel.com/support/articles/using-vercel-cli-for-custom-workflows#using-the-cli-without-project-linking) and since that pretty much addresses how to properly authenticate the Vercel CLI for deployments without using the deprecated `--name` option, I changed the way `DEPLOYMENT_URL` is obtained, and my updated `deploy-to-vercel` job looks like this:

```yml
deploy-to-vercel:
  stage: deploy
  image: node:14-alpine

  variables:
    PREVIEW_URL: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.$VERCEL_USER.vercel.app
    VERCEL_ORG_ID: $VERCEL_ORG_ID
    VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID

  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'

  environment:
    name: vercel/$CI_COMMIT_REF_NAME
    url: https://$PREVIEW_URL

  script:
    - npm i -g vercel
    - DEPLOYMENT_URL=$(VERCEL_ORG_ID=$VERCEL_ORG_ID VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID vercel --confirm -t $VERCEL_TOKEN --scope $VERCEL_USER)
    - vercel alias set $DEPLOYMENT_URL $PREVIEW_URL -t $VERCEL_TOKEN --scope $VERCEL_USER
```

Where `$VERCEL_ORG_ID` and `$VERCEL_PROJECT_ID` come from the `.vercel` folder that’s created when you authenticate the Vercel CLI on your local environment (don’t commit this to git!) and were added as variables on the GitLab project.

### Notes
I changed two things from the original config:

1. I removed the `if: $CI_MERGE_REQUEST_IID` because this was duplicating deployments when I created a merge request, the default behavior is that the last commit of that MR already has a deployment so no extra one needed :)
2. Renamed `$VERCEL_SCOPE` to `$VERCEL_USER` because in my case it better reflects that I’m deploying to a personal account, you don’t have to change it yourself.

**Reply by SinaKarimi7** [reply]
Well done @oxfist, but why did you reinitialize that `VERCEL_ORG_ID` and `VERCEL_PROJECT_ID`? Because the `.vercel` file must be ignored?

**Reply by oxfist** [reply]
@SinaKarimi7 Exactly! Since there's no `.vercel` folder available on CI (which is correct), the way to do it is to explicitly pass both variables for the deployment to work. On this case, they are used to authenticate to Vercel and obtain the URL then used to deploy.

**Reply by mkbctrl** [reply]
For future readers: Actually since we are talking Gitlab CI, you shouldn't explicitly pass those variables, but add CI variables in the Gitlab itself, they are exposed to pipeline files.

It's also included as step 5 in the shiny new guide: https://vercel.com/support/articles/how-can-i-use-gitlab-pipelines-with-vercel#configuring-gitlab-ci/cd-for-vercel

**Comment by leerob** [comment, marked as answer]
**Update:** It's now much easier to deploy to Vercel with any custom CI/CD provider like self-managed GitLab with GitLab Pipelines!

[We've created a guide](https://vercel.com/support/articles/how-can-i-use-gitlab-pipelines-with-vercel) and [an example](https://github.com/vercel/examples/tree/main/ci-cd/gitlab-cicd) using GitLab Pipelines. Hope this helps! 🙏

**Reply by mkbctrl** [reply]
Instant feedback: this is the guide I started with, but I still ended up here looking for more in depth understanding :))
My current plan is to merge what's in above comments with what the example provides. Will try to share if it will be worth it.

**Reply by leerob** [reply]
Would love to hear if the guide isn't solving your needs - please let me know.

**Reply by mkbctrl** [reply]
This is my first approach to it, so it's not production grade yet, still feedback always appreciated:

```
default:
  image: node:16.16.0

# https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Jobs/SAST.gitlab-ci.yml
include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

cache: &global_cache
  untracked: true
  key:
    files:
      - yarn.lock
    prefix: cache
  paths:
    - node_modules
  policy: pull

.test:
  stage: test
  needs:
    - install

.deploy:
  stage: deploy
  cache:
    <<: *global_cache
    policy: pull-push
    paths:
      - .next/cache/
  needs:
    - test_lint
    - test_unit
    - test_typescript

install:
  stage: build
  cache:
    # inherit all global cache settings
    <<: *global_cache
    policy: pull-push
    when: always
  script:
    - echo "Installing dependencies..."
    - yarn install --frozen-lockfile

test_lint:
  extends: .test
  script:
    - echo "Linting..."
    - yarn lint

test_typescript:
  extends: .test
  script:
    - echo "Checking typescript..."
    - yarn tsc --noEmit

test_unit:
  extends: .test
  script:
    - echo "Unit testing..."
    - yarn test_unit --passWithNoTests

deploy_preview:
  extends: .deploy
  variables:
    VERCEL_ENV: preview
  except:
    - main
  script:
    - echo "Deploy preview build..."
    - yarn vercel pull --yes --environment=$VERCEL_ENV --token=$VERCEL_TOKEN
    - yarn vercel build --token=$VERCEL_TOKEN
    - yarn vercel deploy --prebuilt  --token=$VERCEL_TOKEN

deploy_production:
  extends: .deploy
  variables:
    VERCEL_ENV: production
  only:
    - main
  script:
    - echo "Deploy production build..."
    - yarn vercel pull --yes --environment=$VERCEL_ENV --token=$VERCEL_TOKEN
    - yarn vercel build --prod --token=$VERCEL_TOKEN
    - yarn vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

```

@leerob your tutorial is great to setup and go, however my assumption is, that if you are going to use Gitlab, most probably the pipeline itself will be more complex. I totally get that non of the stages other than deploy have anything to do with Vercel, so maybe official tutorial is not the best place for it, maybe an example (thinking out loud). Also we are kind of leaving the frontend department and heading towards dev-ops realm...

However I can imagine that a lot of folks starting their Vercel + Gitlab journey will start with that tutorial (as I did), so I guess that the least we can do is to pinpoint them in the right direction.

When building the pipeline I had to grasp the following concepts:
1. https://docs.gitlab.com/ee/ci/ --> focusing on building blocks: what pipeline, job, stage are and how can I use templates if they exist.
Also adding a cache is pretty important part as well.

Suplements:
2. https://docs.gitlab.com/ee/ci/yaml/index.html#cache
3. https://nextjs.org/docs/advanced-features/ci-build-caching
4. https://docs.gitlab.com/ee/ci/variables/
5. https://about.gitlab.com/webcast/7cicd-hacks/
6. https://about.gitlab.com/topics/ci-cd/continuous-integration-best-practices/
7. https://docs.gitlab.com/ee/ci/pipelines/pipeline_efficiency.html

To put it in a nutshell, I think it would add a great value to describe some basic concepts with "read more" resources included, so it's easier to grasp what's going on, what's optional, and what should be included if we are talking "production grade", including examples with Jest or Cypress and parallel test execution, etc.

**Reply by mkbctrl** [reply]
Also another idea, is to be able to incorporate the `Vercel: external` build step into pipeline, by including a template or connecting it with my pipeline anyhow. It's not possible atm if I understood correctly, but it makes sense for me to reuse your Gitlab integration as much as possible since it's just great in terms of all the bells and whistles like posting summaries inside Gitlab MR's, allowing other integrations to do stuff inside the Gitlab or linking git branches in the project overview --> which is replaced by "via Vercel CLI" if you are not using it.

I am talking about smth like that:
```
deploy_production:
  extends: VercelTemplate
  script:
    - echo "Deploy production build..."
    - yarn vercel pull --yes --environment=$VERCEL_ENV --token=$VERCEL_TOKEN
    - yarn vercel build --prod --token=$VERCEL_TOKEN
    - yarn vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
   needs:
    - my_very_important_job1
    - my_very_important_job2
```

in order to make Vercel deploy wait, and proceed only upon success.
Let me know what you think of it, and if there is a way to make it work, but I am just not aware of it, please share :))
