### DISCUSSION TITLE
How to unshallow repo?

### DISCUSSION THREAD

**Discussion by klarkc** [vercel/vercel#5737] [Help]
Hello, I need to define a variable at build time that depends on `git describe` which depends on git history, but it seems the repo in vercel build enviroment is a shallow clone with [only few last commits](https://vercel.com/knowledge/how-do-i-use-the-ignored-build-step-field-on-vercel). I tried to run a git fetch before build command with no luck:

`git fetch --depth=100 --tags; SENTRY_RELEASE=$(git describe)  yarn build`

`fatal: No names found, cannot describe anything.`

I've also tried with `git fetch --unshallow`, `git fetch --prune --unshallow` and `git fetch --prune --unshallow --tags`.

In my local tests, replicating `git clone --depth=2`, the fetch with `--depth` option is working (even without `--tags`, because tags comes along commits)

**Comment by badazz91** [comment]
Hello, I have the same issue with integrating Chromatic into the build step of vercel. 

14:42:10.542 | > chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --exit-zero-on-changes
-- | --
14:42:12.144 | Chromatic CLI v5.6.1
14:42:12.144 | https://www.chromatic.com/docs/cli
14:42:12.161 | Authenticating with Chromatic
14:42:12.162 | → Connecting to https://index.chromatic.com
14:42:12.497 | Authenticated with Chromatic
14:42:12.497 | → Using project token '********d282'
14:42:12.498 | Retrieving git information
14:42:12.529 | → ✖ Found only one commit
14:42:12.529 | This typically means you've checked out a shallow copy of the Git repository, which some CI systems do by default.
14:42:12.529 | In order for Chromatic to correctly determine baseline commits, we need access to the full Git history graph.
14:42:12.529 | Refer to your CI provider's documentation for details.
14:42:12.533 | ✖ Failed to retrieve git information
14:42:12.533 | ✖ Found only one commit


Is there a way to change the vercel configration, so that the repo is checked out in an unshallow way?

**Comment by badazz91** [comment]
@klarkc I also raised the issue with the Vercel support - here the answer:

[...]

Thank you for reaching out,

I looked into your issue and it turns out that there is indeed a limit to the git history that Vercel accesses.  

We just clone the repo with the parameter depth=2 and **it is not possible to change that**. [Here](https://vercel.com/knowledge/how-do-i-use-the-ignored-build-step-field-on-vercel) is a little more info on the matter.

[...]

**Reply by klarkc** [reply]
Still... Why the `git fetch  --depth` is not working? When I do a git clone with depth 2, then `git fetch --depth` it download the history, fetching more commits, but in vercel enviroment this somehow don't happens.

**Reply by graup** [reply]
Bump

Related topic: https://github.com/vercel/vercel/discussions/7093

**Comment by Styren** [comment]
Is there any way (hacky or not) to manually unshallow a repo? It's just so powerful to get access to the history during build stage, we could for example embed the publishing date of an article by just looking at its first revision.

**Reply by amyegan** [reply]
Disclaimer: I have not personally tested this idea. But you might be able to do something like that by making use of the latest [Build Output API](https://vercel.com/docs/build-output-api/v3) to do a prebuilt deploy from local or CI. 

Some resources that might help if you want to give it a try:
- [Announcing the Build Output API](https://vercel.com/blog/build-output-api)
- [How can I use GitHub Actions with Vercel?](https://vercel.com/guides/how-can-i-use-github-actions-with-vercel)

**Reply by jontyk** [reply]
@amyegan I have just tested and confirmed that the above works, as simple as [this](https://github.com/openline-ai/openline.ai/blob/otter/.github/workflows/preview.yml) for a Docusaurus2 site.

**Reply by brycewray** [reply]
In essence, the choice goes like this:

- Publish to Vercel via the Vercel GUI and get whatever benefits config (`vercel.json`) provides — *e.g.*, control over `Cache-Control` and other headers — but you can’t control `fetch-depth`.
- Publish to Vercel via a GitHub Action and get your desired `fetch-depth`, but `vercel.json` obviously gets ignored and you thus lose what it gave you.

Not pretty. I guess if you’re using Next.js you have other options, but not otherwise.

**Reply by jontyk** [reply]
Is that necessarily true @brycewray? I am using [rewrites via the `vercel.json`](https://github.com/openline-ai/openline.ai/blob/otter/vercel.json) file with no ill effects caused by using the Build Output API via Github actions afaik.

**Reply by brycewray** [reply]
@jontyk It may depend on the use case, of course. In my case, I was building a Hugo site (with an all-npm workflow, using [Hugo Installer](https://github.com/dominique-mueller/hugo-installer), in case that matters). Since all the repo-cloning building took place within GH and the results then were presented to Vercel using [deploy-to-vercel-action](https://github.com/Betahuhn/deploy-to-vercel-action), the Vercel system would — I presume — have no opportunity to “see” `vercel.json`. At least, the results didn’t show that to be the case; the deploy was fine but the headers I specified in `vercel.json` weren’t there.

Here is the action I used, for reference (I have removed some comments, for easier reading):

```
name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Fetch **all** history (not just deploy commit) for Hugo's .GitInfo and .Lastmod
          # See https://discourse.gohugo.io/t/problems-with-gitinfo-in-ci/22480
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install packages
        run: npm install
      - name: Build site with Hugo
        run: npm run build
      - name: Move "excerpts" feed (RSS/Atom only)
        run: mv public/posts/index.xml public/index-excerpts.xml
      - name: Run Pagefind
        run: npm run search
      - name: Publish to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_STATIC_SITE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
          WORKING_DIRECTORY: 'public'
```
