### DISCUSSION TITLE
Authentication

### DISCUSSION THREAD

**Discussion by standbyoneself** [vercel/vercel#6446] [Help]
I have a project and a CircleCI Cloud where are my tests running. I wanna deploy my app only after the tests have passed so I disable auto-deploy on Vercel on each push into the GitHub repo.

I jumped into docs and undesrtood that it is possible by manually POST builded files but I really disappointed since each request requires a Bearer token, but how I can take that?

Reading <https://vercel.com/docs/integrations#using-the-vercel-api/getting-an-access-token> does nothing because I really don't understand where I should get the `client_id`, `client_secret`, `code`, `redirect_uri`. Are the docs deprecated?

And a second question: can I really build the project after passing tests and deploy it using Vercel API? Any tutorial / tips for that? My circleci config:

```yml
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.28.0
jobs:
  install_deps:
    docker:
      - image: circleci/node:12.19.0
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn --ignore-engines
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/
          paths:
            - ./
  test_unit:
    docker:
      - image: circleci/node:12.19.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Tests
          command: yarn test:unit
  trigger_deploy:
    docker:
      - image: circleci/node:12.19.0
    steps:
      - run: curl https://api.vercel.com/v1/integrations/deploy/prj_NYWYUfYnAUpkyoWeGnLqJVh7L0Ei/w1vAP06xFG
workflows:
  default:
    jobs:
      - install_deps
      - test_unit:
          requires:
            - install_deps
      - cypress/run:
          requires:
            - install_deps
          attach-workspace: true
          start: yarn dev
      - trigger_deploy:
          requires:
            - test_unit
            - cypress/run
          filters:
            branches:
              only:
                - master
```

As you can see I have tried just to trigger deploy via git hook but it doesn't work because there is `vercel.json` with `github { "enabled": false }` and I am looking for a manual-deploy solution
