### DISCUSSION TITLE
custom domain does not point to latest preview deployment

### DISCUSSION THREAD

**Discussion by Kohei909Otsuka** [vercel/vercel#6517] [Help]
I use custom domain for main branch like below.

![Cursor_と_wakame_–_Domains_–_Vercel](https://user-images.githubusercontent.com/11783802/126885553-738cfc3f-973f-4e2c-90db-c33244ca1523.png)

then deploy via vercel cli from gcp cloud build(CI) without github auto connection like

```
  - name: node:16
    id: ssr_deploy
    waitFor: ["api_deploy"]
    entrypoint: /bin/sh
    env:
      - "VERCEL_PROJECT_ID=${_VERCEL_PROJECT_ID}"
      - "VERCEL_ORG_ID=${_VERCEL_ORG_ID}"
    args:
      - "-c"
      - |
        npm i -g vercel &&\
        vercel --confirm --token ${_VERCEL_TOKEN} \
       {some env vars here}
```

The problem is ,after the deploy success preview url like `https://wakame-xxxx-tech2-inc.vercel.app/` works fine,
but `hoge.com` doest not reflect a change.

It seems `custom domain => latest preview deployment` alias is not working.

Can anyone help with this?

https://vercel.com/blog/branch-domains
