### DISCUSSION TITLE
GitHub Actions Deployment "Error! Could not find deployment"

### DISCUSSION THREAD

**Discussion by Yota-K** [vercel/vercel#6633] [Help]
I always get the following error when trying to deploy using Github Actions.

```
Vercel CLI 23.1.2
Error! Could not find deployment

Error! Could not find deployment
Error: The process '/opt/hostedtoolcache/node/14.17.5/x64/bin/npx' failed with exit code 1
```

The `deploy.yml` looks like this.

```yml
name: deploy-website
on:
  workflow_dispatch:
    inputs:
      ref:
        description: branch|tag|SHA to checkout
        default: 'main'
        required: true
  schedule:
    - cron:  '10 0 * * *'

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: amondnet/vercel-action@v20
        with:
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod -f -b TZ=Asia/Tokyo -b ENDPOINT=${{ secrets.ENDPOINT }}'
```

I've confirmed that env is correct.

I searched for a solution but couldn't find any information.
If you know the solution, please let me know.

**Comment by NullSoldier** [comment]
This is due to the fact that your personal token cannot see org deployments. I haven't found a workaround for this.

**Reply by NullSoldier** [reply]
Actually you can fix this by setting the scope to your org using the --scope command to the org under the resource that you want to access.

**Comment by kiliw** [comment]
Hello all together,
I tried to use the vercel github action and integrate it in our pipeline. Unfortunately I always get the error that the deployment can t be found. So far everything works and I can visit the page if go to vercel directly. But still the actions fails.
I tried the solution mentioned by @NullSoldier but I cant get it to work. Any ideas how to fix this?
```
.
.
.
  web-deploy:
    runs-on: ubuntu-latest
    needs: [ prepare, web-type-check, web-lint, web-test, build-and-deploy-backend]
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: '--scope=myOrganisation' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
```
