### DISCUSSION TITLE
Send branch ref in Github `deployment` and `deployment_status` events

### DISCUSSION THREAD

**Discussion by jimCresswell** [vercel/vercel#7581] [Ideas]
Hi,

I'm building a fairly large project, currently hosted on Vercel. I want to trigger a suite of automated checks against PR preview deployments (and production deployments) triggered by pushes and PRs in Github.

I have that working, using the Vercel-Github integration, and Github workflows triggered on Github `deployment_status` events. However, within those events, both the `ref` and the `sha` field are set to the value of the SHA of the commit that triggered the build.

That means that within the Github workflow the context/env variable for the ref is undefined, e.g. `GITHUB_REF=""`. That means the Github action `actions/setup-node` cannot be used with caching, see https://github.com/actions/cache/issues/319 .

The lack of caching for Node dependencies significantly slows down Github CI/CD workflows triggered by Vercel deploys.

All of those deployments have an associated branch, either directly or as the head branch (feature branch) in the PR. Would it be possible to send that information in the ref field of the Github `deployment` and `deployment_status` events?

**Comment by danielgent** [comment]
This would make our DX so much better. For our CI/CD we need to set the current deploy URL as the Auth0 callback URL in an env var *except* on `develop` and `main`.

Doesn't currently look possible to do this

There are also other things like building Storybook on Vercel in the same repo.  The Cypress CI/CD tests also fire for that as there's no way to differentiate in GitHub actions where the Vercel build has come from 🥲

**Reply by jimCresswell** [reply]
@danielgent depending on what your Storybook project in Vercel is called, you might be able to do something like
```yaml
my_brilliant_job:
    # Only want to run on success, otherwise it might be "pending", or "failure".
    # Filter out non product deployments
    if: ${{ (github.event.deployment_status.state == 'success') &&  !contains(github.event.deployment_status.environment, 'storybook') }}
    steps:
```

**Reply by danielgent** [reply]
In `github.event.deployment_status.environment`  I get `Preview`  

I'm echoing this out now so when I do a prod release I will see what it shows. I'm guessing `Production`

I wasn't aware we could set up different environments in Vercel. I thought it was only `Preview`, `Development` and `Production` (and development is only for running locally in dev mode)

**Reply by jimCresswell** [reply]
I would have expected something like `Preview - <name of your Vercel project>` but maybe we have different set ups

**Comment by rkreicbergs-sorsera** [comment]
Is there any update on this from Vercel side? Are we missing something? This seems like an obvious thing to do - if a commit on a specific branch trigger deployment, then Vercel should provide the same info back on `deployment_status` event. Is there a way to detect the branch from the event?

Our problem. We use stage and production environments, each with a fixed domain. We don't have an issue for production environment, but we keep struggling with properly setting up a stage environment. For the app itself, we use NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF to recognize both stage and production environments. But we cannot figure out how to properly run E2E tests for Stage. We can detect production environment using `github.event.deployment_status.environment` and for feature branches we use *.vercel.app URLs, but we cannot figure out how to propely run our Staging E2E tests with the proper custom domain we have assigned to it.

**Reply by jimCresswell** [reply]
@rkreicbergs-sorsera you can dump out the entire GitHub event metadata with a re-usable workflow like
```yaml
# .github/workflows/reusable/dump_event.yml
on:
  workflow_call:

jobs:
  run:
    name: dump GitHub event
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo GITHUB_ACTION: $GITHUB_ACTION
          echo GITHUB_WORKFLOW: $GITHUB_WORKFLOW
          echo GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
          echo GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
```

and then use it like

```yaml
name: Deployment Status Actions

on: deployment_status

jobs:
  dump_github_event:
    uses: ./.github/workflows/reusable/dump_event.yml
```

that should show you all the data you have to play with. You can also write a custom JavaScript action to determine the branch a commit came from by comparing the commit to the HEAD of each branch, odds are only one branch has the commit you care about as its HEAD.
