### DISCUSSION TITLE
Are GIT_* variables available when using the CLI to deploy?

### DISCUSSION THREAD

**Discussion by gsheppard** [vercel/vercel#8402] [Help]
I switched from using the Vercel for Github integration to manually deploying via Github Actions + Vercel CLI. But when I did that, I lose all the `GIT_*` environment variables.

Is this intended, or is there a piece of setup I am missing? Currently they are all blank after running `vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}`. Other variables that are manually set in Vercel settings are still pulled down.

My Vercel-specific steps in my workflow (which is part of a matrix to deploy 3 apps):
```
- name: Pull Vercel Environment Information
  run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
  env:
    VERCEL_PROJECT_ID: ${{ secrets[matrix.app.project_id] }}

- name: Build Project Artifacts
  run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
  env:
    VERCEL_PROJECT_ID: ${{ secrets[matrix.app.project_id] }}

- name: Deploy Project Artifacts to Vercel
  run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
  env:
    VERCEL_PROJECT_ID: ${{ secrets[matrix.app.project_id] }}
```
