### DISCUSSION TITLE
Comments for deployments on PRs when deploying with Vercel CLI

### DISCUSSION THREAD

**Discussion by IGassmann** [vercel/vercel#9065] [Ideas]
Vercel allows users to [use GitHub Actions to build and deploy](https://vercel.com/guides/how-can-i-use-github-actions-with-vercel) thanks to the Vercel CLI. GitHub Actions are a great solution for when you have complex deployment pipelines, and you want to clearly display the steps that are performed along the way on GitHub.

However, if you decide to use GitHub Actions for deploying to Vercel, the Vercel bot won't comment on open PRs the link to the preview deployment with information about the number of [comments on the Preview Deployment](https://vercel.com/docs/concepts/deployments/comments):

![image](https://user-images.githubusercontent.com/4291707/206862723-04d014db-46ae-4858-84ef-200eb2524524.png)

**Comment by amyegan** [comment]
Great idea! I think the team is already working on some features that could make this possible. I'll make sure it's on the requested features list 😄

**Reply by defunctzombie** [reply]
Great to hear!

Is there a workaround the team would recommend to surface the deployment URL to the PR? Right now the only place I can find the URL is by clicking into the action and searching through the action logs.

**Comment by frdwhite24** [comment]
Great to hear the team is working on this, are there any updates on this? @defunctzombie @IGassmann did either of you come up with a solution?

**Reply by psirenny** [reply]
I'm interested in this as well!

**Reply by amyegan** [reply]
~~Comments should already be working now with preview deployments via CLI. I just checked with a couple of my own sites and it is working for me on deployments made via CLI, Deploy Hooks, and GitHub integration.~~ See update below.

**Reply by frdwhite24** [reply]
Interesting, may I ask how you've configured this? for clarity here is what we've done:

- We have the Github Vercel integration connected to our Github repo
- We're using the "Ignored Build Step" command for all of our projects with the command `exit 0` so that automatic on push previews and deploys aren't triggered
- We're then deploying the preview using [this guide](https://vercel.com/guides/how-can-i-use-github-actions-with-vercel) in one of our self-hosted Github Action jobs.

Currently we're seeing in the Vercel section under the PR description that builds have been ignored (albeit in a flaky manner, sometimes all 3 of our projects are ignored, sometimes 1-3 of them just sit in "Pending" state as if they are still carrying out the auto deploy despite the `exit 0` command)

Any guidance/reference to docs would be welcomed and thanks in advance!

**Reply by amyegan** [reply]
I apologize, I was looking at the wrong thing. 🤦 The PR comments don't seem to come through automatically unless using the Vercel GitHub integration to deploy.

But I am getting a PR comment with the deployment URL because of my workflow setup. I included an `Add-Comment` job to include the URL in a comment on the PR after deployment is complete.

```yaml
name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    types: [opened, reopened, edited]
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    outputs: 
      deploymentUrl: ${{ steps.deploy-step.outputs.deploymentUrl }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy-step
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} >deployment-url.txt
          echo "deploymentUrl=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT
  Add-Comment:
    runs-on: ubuntu-latest
    needs: Deploy-Preview
    permissions: 
      issues: write
      pull-requests: write
    steps:
      - name: Comment URL to PR
        env: 
          DEPLOYMENT_URL: ${{needs.Deploy-Preview.outputs.deploymentUrl}}
        uses: actions/github-script@v6
        id: my-script
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Deployed at ${{env.DEPLOYMENT_URL}}"
            })

```

**Reply by defunctzombie** [reply]
@frdwhite24 Here's a snipped of the workflow we use to deploy to vercel from github actions and display preview URLs in the github PR using the "environments" feature on github:

Note: We have disabled the vercel github integration and do all of our builds via github actions. It was important to us to do vercel deployments after tests for production deployments.

```
jobs:
  Deploy:
    runs-on: ubuntu-latest

    environment:
      name: preview
      url: ${{ steps.seturl.outputs.url }}

    steps:
      - uses: actions/checkout@v3.5.3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        shell: bash
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | tee deploy.log

      - id: seturl
        name: Set preview url
        run: echo "url=$(tail -1 deploy.log)">> $GITHUB_OUTPUT

      - run: echo "${{ steps.seturl.outputs.url }}"
```

We don't use the comments feature of vercel so don't need those comments on our PRs.

**Reply by frdwhite24** [reply]
Thanks so much both @defunctzombie and @amyegan, this looks like it's exactly what we'd need and agreed @defunctzombie re deployments after tests for production. I'll implement something when i next get a chance and revert back here 😊

**Reply by frdwhite24** [reply]
@amyegan do you have a personal access token for Vercel CLI hooked into the Github Action for this?

I'm just wondering because previously we have had Preview URLs being in the format of `<app-name>-git-<branch-name>-netpurpose.vercel.app` but now they're all in the format `<app-name>-frdwhite24-netpurpose.vercel.app` so overlap across branches. Commit specific URLs are unique as they use the git SHA.

Your solution: does it comment the commit specific URL or the branch URL? If commit specific, does that mean you get N commits * X deploys = number of comments? i.e. 3 deploys on a mono repo, 10 commits would be 30 comments on the PR 🤪

Would be fantastic to either edit an existing comment, or sustain the unique deployment URL per branch as per with the Vercel Integration! What are your thoughts?

**Reply by paul-vd** [reply]
You could check if the comment exists and then update it? for example:

```yml
name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment: preview
    outputs:
      deploymentUrl: ${{ steps.deploy.outputs.deploymentUrl }}
    steps:
      - name: Checkout the Codebase
        uses: actions/checkout@v3

      - name: Environment Setup
        uses: ./.github/actions/environment-setup

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          export NODE_OPTIONS="--max-old-space-size=7168"
          vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deploy.log
          URL=$(cat deploy.log | grep -o 'https://[^ ]*.vercel.app' | head -n1)
          echo "deploymentUrl=$URL" >> $GITHUB_OUTPUT

  Add-Comment:
    runs-on: ubuntu-latest
    needs: Deploy-Preview
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Comment URL to PR
        uses: actions/github-script@v6
        id: comment-deployment-url-script
        env:
          DEPLOYMENT_URL: ${{ needs.Deploy-Preview.outputs.deploymentUrl }}
        with:
          script: |
            // Get pull requests that are open for current ref.
            const pullRequests = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`
            })

            // Set issue number for following calls from context (if on pull request event) or from above variable.
            const issueNumber = context.issue.number || pullRequests.data[0].number

            // Retrieve existing bot comments for the PR
            const {data: comments} = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
            })
            const botComment = comments.find(comment => {
                return comment.user.type === 'Bot' && comment.body.includes('Deployed at')
            })

            const output = "Deployed at " + process.env.DEPLOYMENT_URL

            // If we have a comment, update it, otherwise create a new one
            if (botComment) {
                github.rest.issues.updateComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    comment_id: botComment.id,
                    body: output
                })
            } else {
                github.rest.issues.createComment({
                    issue_number: issueNumber,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: output
                })
            }

```
