### DISCUSSION TITLE
How to update preview URL from CLI?

### DISCUSSION THREAD

**Discussion by RareSecond** [vercel/vercel#9161] [Help] [answered]
Since we want to start using tags for deployments, we were forced to use the Vercel CLI in combination with GitLab CI to get our project up and running again.

However, one handy feature that we are now missing is the ability to automatically have a comment with the preview URL on GitLab MRs. I want to recreate this, but my CI keeps telling me that I need to reauthenticate (whereas all the other steps are executed successfully).

This is the current code

```
deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7.11.0
    - pnpm config set store-dir .pnpm-store
    - pnpm install
    - pnpm vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - pnpm vercel build --token=$VERCEL_TOKEN
    - pnpm vercel deploy --prebuilt  --token=$VERCEL_TOKEN > domain.txt
    - pnpm vercel alias --token=$VERCEL_TOKEN set `cat domain.txt` myproject-mybranch-myorg.vercel.app
```

Where the `myproject` and `myorg` are filled in with our details.

However, this is the output I get from the CLI:

```
$ pnpm vercel alias --token=$VERCEL_TOKEN set `cat domain.txt` myproject-mybranch-myorg.vercel.app
Vercel CLI 28.10.1
> You must re-authenticate to use jasper64 scope.
> Log in to Vercel (Use arrow keys)
❯ Continue with GitHub 
  Continue with GitLab 
  Continue with Bitbucket 
  Continue with Email 
  ───────────────────────
  Cancel undefined
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command was killed with SIGINT (User interruption with CTRL-C)
```

What am I doing wrong?
Am I trying to do something that's not supported?

I came across https://github.com/vercel/vercel/discussions/4853 and it seems I'm using the same steps, but not sure why I'm getting a failure.
