### DISCUSSION TITLE
How to access vercel deployment URL while deploying with github actions?

### DISCUSSION THREAD

**Discussion by anstill** [vercel/vercel#9488] [Help] [answered]
My github workflow: 

```yml
name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  Deploy-Preview:
    environment:
      name: preview
      url: ${{ steps.deployment.outputs.vercel_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
```

I want to access vercel deployment URL something like this `url: ${{ steps.deployment.outputs.vercel_url }}`
