### DISCUSSION TITLE
Vercel CLI does not inject proper environments(prod, preview) on build

### DISCUSSION THREAD

**Discussion by kasvith** [vercel/vercel#9797] [Help] [answered]
### Problem Description

We are running vercel cli on Github actions with the following steps

```yaml
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
```

and when we check the deployment, it doesn't have any environment variables we defined in the production environment.

we have used `NEXT_PUBLIC_VAR_NAME` as variables for Next to pickup. It just doesn't work

I checked to build it locally, it got the same result. CLI correctly creates `.env.production` file inside `.vercel` folder.
But it doesn't inject them into the build
