### ISSUE TITLE
Setting alias to custom domain from Circle CI doesn't seem to work

### ISSUE THREAD

**Issue by granmoe** [vercel/vercel#1015]
I have the following circle ci config.yml:

```yml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run: sudo npm install -g now@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "web/package.json" }}
      - run: |
          cd web
          npm install
      - save_cache:
          key: dependency-cache-{{ checksum "web/package.json" }}
          paths:
            - ./web/node_modules
      - run: |
          cd web
          npm test
      - run: |
          cd web
          npm run build
      - deploy:
          working_directory: web
          command: |
              now -t ${NOW_TOKEN}
              now -t ${NOW_TOKEN} alias
```

I've set my NOW_TOKEN for the project, and that part is working. I've also seen the appropriate deployment logs in my now.sh dashboard after each circle job runs. However, the aliasing never seems to have any effect. I have the now.alias property set in my package.json. 

See the entire repo here:

https://github.com/granmoe/basho

This is a (small) monorepo, and the project I'm having these issues with is in the web directory. I have no idea what I'm doing wrong. I've followed the now.sh and circle ci docs to a tee (as far as I can tell).

I've also stopped getting any logs whatsoever in the now.sh dashboard as of 2 days ago.
