### ISSUE TITLE
Token authentication for rm appears to be broken

### ISSUE THREAD

**Issue by spences10** [vercel/vercel#1072]
`rm` doesn't appear to be working for my CI with TravisCI

Log from [CI](https://travis-ci.org/spences10/blog.scottspence.me/jobs/328487903#L4622) 
Excerpt:
```sh
$ now run cleanup
> Error! No existing credentials found. Please run "now login" or pass "--token"
> More details: https://err.sh/now-cli/no-credentials-found
```

I have tried the following combinations:

`"cleanup": "now rm scottblog --safe --yes --token $NOW_TOKEN",`
`"cleanup": "now rm scottblog --safe --yes --token$NOW_TOKEN",`
`"cleanup": "now rm scottblog --safe --yes --token=$NOW_TOKEN",`

Removing some lines for brevity **`.travis.yaml`:**
```yaml
script:
  - npm i -g now@canary
  - npm run clean
  - npm run build
  - npm run deploy
after_script: 
  - if [ "$TRAVIS_BRANCH" = "development" ]; then npm run alias:dev; fi 
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run alias:prod; fi
  - now run cleanup
```

My **`package.json`:**
```json
    "deploy": "now scottblog/ --token $NOW_TOKEN",
    "alias:dev": "now alias scottspence.now.sh --token $NOW_TOKEN",
    "alias:prod": "now alias blog.scottspence.me --token $NOW_TOKEN",
    "cleanup": "now rm scottblog --safe --yes --token=$NOW_TOKEN",
```

This seems similar to #804 but it is specifically the `rm` function, `alias` and `now` are working as expected.

Let me know if there is anything else you need  👍
