### ISSUE TITLE
Django application results in 503

### ISSUE THREAD

**Issue by quorth0n** [vercel/vercel#1471]
When deploying my Django application to Now, no errors are returned, and my app appears to have successfully deployed. However, when navigating to the returned URL, the request either times out or returns a 503. This occurs both when running `now` and `now --no-verify` I can successfully run the application on port 80 on my local machine with `docker-compose up -d`

Dockerfile:
```dockerfile
FROM python:3.6-alpine
ENV PYTHONUNBUFFERED 1  

RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev bash

RUN mkdir /config  
ADD /config/requirements.txt /config/  
RUN pip install -r /config/requirements.txt
RUN mkdir /src
WORKDIR /src
EXPOSE 80
```
docker-compose.yml:
```yml
version: '3'
services:
  db:
    image: mdillon/postgis:10-alpine
    container_name: postgres01
  nginx:
    image: nginx:1.13-alpine
    container_name: nginx01
    ports:
      - "80:80"
    volumes:
      - ./project:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: django01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn interactivemap.wsgi -b 0.0.0.0:80"
    depends_on:
      - db
    volumes:
      - ./project:/src
    expose:
      - "80"
    restart: always
```
/config/nginx/django.conf
```nginx
upstream web {
   ip_hash;
   server web:80;
}

# portal
server {
  location / {
        proxy_pass http://web/;
    }
  listen 80;
  server_name localhost;

  location /static {    
    autoindex on;    
    alias /src/static/;    
  }
}

```
```
> Deploying backend under whirish

> https://backend-qdirzaaqyr.now.sh [in clipboard] (sfo1) [582ms]
> Success! Deployment ready
```
