### ISSUE TITLE
Travis deployments fails with error "Error: Option requires argument: --token"

### ISSUE THREAD

**Issue by sanishtj** [vercel/vercel#1632]
I have a react app in express. I am trying to deploy it on now and followed the steps from this [link](https://zeit.co/docs/continuous-integration/travis?utm_source=twitter&utm_medium=social&utm_campaign=travis_ci_guide).

Build was successful until I added the scripts into .travis.yml as mentioned in the link.
I can see it has ran until, `before_deploy: npm install now --no-save --unsafe-perm`

Below is the script supposed to be failing,

```
deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: now --token $blahblahblah
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --token $blahblahblah && now alias --token $blahblahblah
    skip_cleanup: true
    on:
      master: true
```

Deployment is failing with below error,

```
travis_fold:end:dpl.2
travis_fold:start:dpl.3
[33mDeploying application[0m
[31m> Error![39m An unexpected error occurred!
  Error: Option requires argument: --token
    at arg (/snapshot/repo/node_modules/arg/index.js:70:12)
    at getArgs (/snapshot/repo/dist/now.js:3155:27)
    at main (/snapshot/repo/dist/now.js:16442:37)
    at Object.<anonymous> (/snapshot/repo/dist/now.js:16903:1)
    at __webpack_require__ (/snapshot/repo/dist/now.js:20:30)
    at /snapshot/repo/dist/now.js:63:18
    at Object.<anonymous> (/snapshot/repo/dist/now.js:66:10)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:650:10)
    at Module.load (module.js:558:32) Error: Option requires argument: --token
    at arg (/snapshot/repo/node_modules/arg/index.js:70:12)
    at getArgs (/snapshot/repo/dist/now.js:3155:27)
    at main (/snapshot/repo/dist/now.js:16442:37)
    at Object.<anonymous> (/snapshot/repo/dist/now.js:16903:1)
    at __webpack_require__ (/snapshot/repo/dist/now.js:20:30)
    at /snapshot/repo/dist/now.js:63:18
    at Object.<anonymous> (/snapshot/repo/dist/now.js:66:10)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:650:10)
    at Module.load (module.js:558:32)

travis_fold:end:dpl.3
Script failed with status 1
failed to deploy
```
