### ISSUE TITLE
Add now.yaml support? 

### ISSUE THREAD

**Issue by fr3fou** [vercel/vercel#1673]
# How about a now.yaml support? 

I'm not a huge fan of making now.json files as writing text files in JSON is annoying, mainly due to the requirement of quotes around each key/value. YAML might be able to mitigate this problem. 

Compare this:

```json
{
  "alias": "nextjsorg.now.sh",
  "type": "static",
  "static": {
    "directoryListing": false,
    "headers": [
      {
        "source": "/_next/static/chunks/*",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "public, max-age=31536000, immutable"
          }
        ]
      },
      {
        "source": "/_next/static/runtime/*",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "public, max-age=31536000, immutable"
          }
        ]
      },
      {
        "source": "/_next/static/commons/**",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "public, max-age=31536000, immutable"
          }
        ]
      },
      {
        "source": "/static/favicon/**",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "public, max-age=31536000, immutable"
          }
        ]
      },
      {
        "source": "/static/images/**",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "public, max-age=31536000, immutable"
          }
        ]
      },
      {
        "source": "/_next/static/*/pages/**/*.js",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "public, max-age=31536000, immutable"
          }
        ]
      }
    ]
  }
}
```

with this:

```yaml
---
alias: nextjsorg.now.sh
type: static
static:
  directoryListing: false
  headers:
  - source: "/_next/static/chunks/*"
    headers:
    - key: Cache-Control
      value: public, max-age=31536000, immutable
  - source: "/_next/static/runtime/*"
    headers:
    - key: Cache-Control
      value: public, max-age=31536000, immutable
  - source: "/_next/static/commons/**"
    headers:
    - key: Cache-Control
      value: public, max-age=31536000, immutable
  - source: "/static/favicon/**"
    headers:
    - key: Cache-Control
      value: public, max-age=31536000, immutable
  - source: "/static/images/**"
    headers:
    - key: Cache-Control
      value: public, max-age=31536000, immutable
  - source: "/_next/static/*/pages/**/*.js"
    headers:
    - key: Cache-Control
      value: public, max-age=31536000, immutable
```

Notice that it's much cleaner and human readable, right?
*hope you don't mind me using the next.js site now.json as an example*

I'd like to hear everyone's thoughts on this.
