### ISSUE TITLE
Region is ignored when deploying with --token

### ISSUE THREAD

**Issue by screendriver** [vercel/vercel#1771]
My `now.json` looks like this:

```json
{
  "version": 2,
  "alias": "itsme",
  "regions": ["bru"]
}
```

And I deploy from my Travis build via

```yaml
deploy:
  - provider: script
    script: yarn now --token $NOW_TOKEN
```

When I deploy locally with `now` it deploys straight to Brussels. But on my Travis build it deploys to Washington DC. What's really strange: in my Travis dashboard logs I can see that it deploys to `[bru1]` but when I look at my Zeit dashboard I see `Washington DC, US East (IAD)` 🤔
