### ISSUE TITLE
How to dynamically alias a service with new alias changes?

### ISSUE THREAD

**Issue by cayasso** [vercel/vercel#307]
I manage multiple environments of a same service, I deploy them using CircleCI, my circle.yml look like this:

```yml
...
...
deployment:
  development:
    branch: master
    commands:
      - now -t $NOW_TOKEN --alias dev-pin.mydomain.com
  production:
    branch: production
    commands:
      - now -t $NOW_TOKEN --alias pin.mydomain.com
```

As you can see the `alias` is dynamic depending on the branch. With the new `alias` change and the deprecation of `--alias` how can I accomplish this same behavior described? The last alias by running `now alias` does not work for me in this particular case.

Thanks!

**Comment by hugomd** [comment]
@cayasso You can accomplish this by using a separate command: `now alias`.

This is how I accomplish it with GitLab CI:
```YAML
deploy:
  stage: deploy
  script:
    - URL=$(now -t ${NOW_TOKEN})
    - now -t ${NOW_TOKEN} alias set ${URL} dev-pi.mydomain.com
```
